language: java
script: mvn -q install -Penable-unit-tests,enable-integration-tests
sudo: false

cache:
  directories:
    - $HOME/.m2
    
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

os:
  - linux

branches:
  only:
    - master
