language: java
os: linux
sudo: false

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jdk:
  - oraclejdk7
  - oraclejdk8

install:
  - mvn clean compile dependency:resolve -U
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean install -Penable-integration-tests ${JDK_PROFILE}
  - mvn com.code-spotter:codespotter-maven-plugin::check
